defaults:
  - _self_
  - trainer: test
  - optimizer: adam
  - lr_scheduler: inv_sqrt_w_linear_ramps
  - model: extended_isotropic
  - data: test_post_neutron_star_merger
  - experiment: finetune_example
  - server: local
  - distribution: local
  - logger: wandb
  - checkpoint: defaults
  - finetuning_mods: test
data_workers: 1
name: test_finetune
finetune: True
automatic_setup: True
experiment_dir: /global/u2/k/khegazy/projects/pde/walrus/walrus/experiments/test